services:
  - type: web
    name: pc-controller-generator
    env: python
    runtime: python-3.11.8
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: GITHUB_TOKEN  
        sync: false
      - key: ADMIN_CHAT_ID
        sync: false
      - key: GITHUB_REPO
        value: "your-username/pc-controller-builder"
